name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.14
        uses: actions/setup-go@v4
        with:
          go-version: ^1.14

      - name: Run go build
        run:
          go build ./client

      - name: Test
        run: go test -json -coverprofile=cover.out ./... > result.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
