name: Golang linter

on:
  push:
    branches-ignores:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read

jobs:
  golang-ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.14'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
